import { MakeLogicType, kea } from 'kea'

import { Dashboard } from './types'

// Generated by kea-typegen. DO NOT EDIT THIS BLOCK MANUALLY.
export interface counterLogicValues {
    counter: number
    dashboard: Dashboard | null
    doubleCounter: number
}

export interface counterLogicActions {
    increment: (amount: number) => {
        amount: number
    }
    setDashboard: (dashboard: Dashboard) => {
        dashboard: Dashboard
    }
}

export type counterLogicType = MakeLogicType<counterLogicValues, counterLogicActions>

export const counterLogic = kea<counterLogicType>({
    path: ['counterLogic'],
    actions: {
        increment: (amount: number) => ({ amount }),
        setDashboard: (dashboard: Dashboard) => ({ dashboard }),
    },
    reducers: {
        counter: [0, { increment: (state, { amount }) => state + amount }],
        dashboard: [null as Dashboard | null, { setDashboard: (_, { dashboard }) => dashboard }],
    },
    selectors: {
        doubleCounter: [(s) => [s.counter], (counter) => counter * 2],
    },
})
