import { MakeLogicType, kea } from 'kea'

export interface ProfileLogicProps {
    id: number
}

// Generated by kea-typegen. DO NOT EDIT THIS BLOCK MANUALLY.
export interface profileLogicValues {
    username: string
}

// Generated by kea-typegen. DO NOT EDIT THIS BLOCK MANUALLY.
export interface profileLogicActions {
    setUsername: (username: string) => {
        username: string
    }
}

export type profileLogicType = MakeLogicType<profileLogicValues, profileLogicActions, ProfileLogicProps>

export const profileLogic = kea<profileLogicType>({
    props: {} as ProfileLogicProps,
    key: (props) => props.id,
    path: (key) => ['profileLogic', key],
    actions: {
        setUsername: (username: string) => ({ username }),
    },
    reducers: {
        username: ['', { setUsername: (_, { username }) => username }],
    },
})
