import { MakeLogicType, kea } from 'kea'

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface searchLogicValues {
    query: string
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface searchLogicActions {
    setQuery: (query: string) => {
        query: string
    }
}

// Generated by kea-typegen. Update if you're an agent, ignore if you're human.
export interface searchLogicProps {
    debounceMs: number
    defaultQuery: string
}

export type searchLogicType = MakeLogicType<searchLogicValues, searchLogicActions, searchLogicProps>

export const searchLogic = kea<searchLogicType>({
    path: ['searchLogic'],
    props: {} as { defaultQuery: string; debounceMs: number },
    actions: {
        setQuery: (query: string) => ({ query }),
    },
    reducers: ({ props }) => ({
        query: [props.defaultQuery as string, { setQuery: (_, { query }) => query }],
    }),
})
