import * as fs from 'fs'
import * as os from 'os'
import * as path from 'path'
import * as ts from 'typescript'
import { AppOptions } from '../types'
import { programFromSource } from '../utils'
import { visitProgram } from '../visit/visit'
import { printToFiles } from '../print/print'

describe('manually typed logics', () => {
    test('skips logics typed with MakeLogicType', () => {
        const logicSource = `
            import { kea, MakeLogicType } from 'kea'

            interface Values { name: string }
            interface Actions { updateName: (name: string) => { name: string } }

            const logic = kea<MakeLogicType<Values, Actions>>({
                actions: () => ({
                    updateName: (name: string) => ({ name }),
                }),
            })
        `
        expect(visitProgram(programFromSource(logicSource)).length).toBe(0)
    })

    test('skips logics typed with a custom local type, even when named like a generated one', () => {
        const logicSource = `
            import { kea, MakeLogicType } from 'kea'

            export type logicType = MakeLogicType<{ name: string }, { updateName: (name: string) => { name: string } }>

            const logic = kea<logicType>({
                actions: () => ({
                    updateName: (name: string) => ({ name }),
                }),
            })
        `
        expect(visitProgram(programFromSource(logicSource)).length).toBe(0)
    })

    test('does not skip local logic types carrying the kea-typegen marker', () => {
        const logicSource = `
            import { kea, MakeLogicType } from 'kea'

            // Generated by kea-typegen. DO NOT EDIT THIS BLOCK MANUALLY.
            export type logicType = MakeLogicType<{ name: string }, { updateName: (name: string) => { name: string } }>

            const logic = kea<logicType>({
                actions: () => ({
                    updateName: (name: string) => ({ name }),
                }),
            })
        `
        const parsedLogics = visitProgram(programFromSource(logicSource))
        expect(parsedLogics.length).toBe(1)
        expect(parsedLogics[0].actions.map((a) => a.name)).toEqual(['updateName'])
    })

    test('does not skip generated blocks where the marker sits on the values interface', () => {
        const logicSource = `
            import { kea, MakeLogicType } from 'kea'

            // Generated by kea-typegen. DO NOT EDIT THIS BLOCK MANUALLY.
            export interface logicValues { name: string }

            export interface logicActions { updateName: (name: string) => { name: string } }

            export type logicType = MakeLogicType<logicValues, logicActions>

            const logic = kea<logicType>({
                actions: () => ({
                    updateName: (name: string) => ({ name }),
                }),
            })
        `
        const parsedLogics = visitProgram(programFromSource(logicSource))
        expect(parsedLogics.length).toBe(1)
    })

    test('does not skip logics with a generated type that does not resolve yet', () => {
        const logicSource = `
            import { kea } from 'kea'

            const logic = kea<logicType>({
                actions: () => ({
                    updateName: (name: string) => ({ name }),
                }),
            })
        `
        expect(visitProgram(programFromSource(logicSource)).length).toBe(1)
    })
})

describe('inline mode', () => {
    const createProgram = (fileNames: string[]) =>
        ts.createProgram(fileNames, {
            module: ts.ModuleKind.CommonJS,
            moduleResolution: ts.ModuleResolutionKind.NodeJs,
            target: ts.ScriptTarget.ES2020,
            skipLibCheck: true,
        })

    test('writes and updates MakeLogicType blocks above the logic', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'kea-typegen-inline-'))

        try {
            const logicDir = path.join(tempDir, 'src')
            const logicPath = path.join(logicDir, 'logic.ts')
            const logicTypePath = path.join(logicDir, 'logicType.ts')
            const keaDtsPath = path.join(tempDir, 'node_modules', 'kea', 'index.d.ts')

            fs.mkdirSync(path.dirname(keaDtsPath), { recursive: true })
            fs.mkdirSync(logicDir, { recursive: true })

            fs.writeFileSync(
                keaDtsPath,
                [
                    'export function kea<T = any>(input: any): T',
                    'export interface MakeLogicType<V = any, A = any, P = any> {}',
                    '',
                ].join('\n'),
            )
            fs.writeFileSync(
                logicPath,
                [
                    "import { kea } from 'kea'",
                    '',
                    'export const logic = kea({',
                    '    props: {} as { id: number },',
                    '    actions: () => ({',
                    '        setValue: (value: string) => ({ value }),',
                    '    }),',
                    '    reducers: () => ({',
                    "        value: ['' as string, { setValue: (_, { value }) => value }],",
                    '    }),',
                    '})',
                    '',
                ].join('\n'),
            )

            const appOptions: AppOptions = {
                rootPath: logicDir,
                typesPath: logicDir,
                packageJsonPath: path.join(tempDir, 'package.json'),
                inline: true,
                write: true,
                log: () => {},
            }

            const program = createProgram([logicPath])
            const parsedLogics = visitProgram(program, appOptions)
            expect(parsedLogics.length).toBe(1)

            const response = await printToFiles(program, appOptions, parsedLogics)
            expect(response.writtenFiles).toBe(1)

            const writtenLogic = fs.readFileSync(logicPath, 'utf8')

            expect(writtenLogic).toContain("import { MakeLogicType, kea } from 'kea'")
            expect(writtenLogic).toContain('// Generated by kea-typegen. DO NOT EDIT THIS BLOCK MANUALLY.')
            expect(writtenLogic).toContain('export interface logicValues {')
            expect(writtenLogic).toContain('export interface logicActions {')
            expect(writtenLogic).toContain('export interface logicProps {')
            expect(writtenLogic).toContain('export type logicType = MakeLogicType<logicValues, logicActions, logicProps>')
            expect(writtenLogic).toContain('export const logic = kea<logicType>({')
            expect(writtenLogic).toContain('value: string')
            expect(writtenLogic).toContain('setValue: (value: string) =>')
            expect(fs.existsSync(logicTypePath)).toBe(false)

            // a second pass over the written file changes nothing
            const secondProgram = createProgram([logicPath])
            const secondParsedLogics = visitProgram(secondProgram, appOptions)
            expect(secondParsedLogics.length).toBe(1)

            const secondResponse = await printToFiles(secondProgram, appOptions, secondParsedLogics)
            expect(secondResponse).toEqual({ filesToWrite: 0, writtenFiles: 0, filesToModify: 0 })
            expect(fs.readFileSync(logicPath, 'utf8')).toBe(writtenLogic)

            // adding an action updates the existing block in place
            fs.writeFileSync(
                logicPath,
                fs
                    .readFileSync(logicPath, 'utf8')
                    .replace('setValue: (value: string) => ({ value }),', 'setValue: (value: string) => ({ value }),\n        reset: true,'),
            )

            const thirdProgram = createProgram([logicPath])
            const thirdResponse = await printToFiles(thirdProgram, appOptions, visitProgram(thirdProgram, appOptions))
            expect(thirdResponse.writtenFiles).toBe(1)

            const updatedLogic = fs.readFileSync(logicPath, 'utf8')
            expect(updatedLogic).toContain('reset: ')
            expect(updatedLogic.match(/export type logicType = MakeLogicType</g)?.length).toBe(1)
            expect(updatedLogic.match(/export interface logicValues \{/g)?.length).toBe(1)
            expect(updatedLogic.match(/export interface logicActions \{/g)?.length).toBe(1)
            expect(updatedLogic.match(/DO NOT EDIT THIS BLOCK MANUALLY/g)?.length).toBe(1)
        } finally {
            fs.rmSync(tempDir, { recursive: true, force: true })
        }
    })

    test('replaces the old logicType.ts import when switching to inline mode', async () => {
        const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'kea-typegen-inline-migrate-'))

        try {
            const logicDir = path.join(tempDir, 'src')
            const logicPath = path.join(logicDir, 'logic.ts')
            const logicTypePath = path.join(logicDir, 'logicType.ts')
            const keaDtsPath = path.join(tempDir, 'node_modules', 'kea', 'index.d.ts')

            fs.mkdirSync(path.dirname(keaDtsPath), { recursive: true })
            fs.mkdirSync(logicDir, { recursive: true })

            fs.writeFileSync(
                keaDtsPath,
                [
                    'export function kea<T = any>(input: any): T',
                    'export interface MakeLogicType<V = any, A = any, P = any> {}',
                    '',
                ].join('\n'),
            )
            fs.writeFileSync(logicTypePath, 'export interface logicType {}\n')
            fs.writeFileSync(
                logicPath,
                [
                    "import { kea } from 'kea'",
                    "import type { logicType } from './logicType'",
                    '',
                    'export const logic = kea<logicType>({',
                    '    actions: () => ({',
                    '        setValue: (value: string) => ({ value }),',
                    '    }),',
                    '})',
                    '',
                ].join('\n'),
            )

            const appOptions: AppOptions = {
                rootPath: logicDir,
                typesPath: logicDir,
                packageJsonPath: path.join(tempDir, 'package.json'),
                inline: true,
                write: true,
                delete: true,
                log: () => {},
            }

            const program = createProgram([logicPath])
            const response = await printToFiles(program, appOptions, visitProgram(program, appOptions))
            expect(response.writtenFiles).toBe(1)

            const writtenLogic = fs.readFileSync(logicPath, 'utf8')

            expect(writtenLogic).not.toContain("from './logicType'")
            expect(writtenLogic).toContain("import { MakeLogicType, kea } from 'kea'")
            expect(writtenLogic).toContain('export interface logicActions {')
            // no values or props on this logic, so no interfaces are generated for them
            expect(writtenLogic).toContain('export type logicType = MakeLogicType<{}, logicActions>')
            expect(writtenLogic).toContain('export const logic = kea<logicType>({')
            expect(fs.existsSync(logicTypePath)).toBe(false)
        } finally {
            fs.rmSync(tempDir, { recursive: true, force: true })
        }
    })
})
