package keainspect

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

func EmitTypegen(logics []ParsedLogic) string {
	return EmitTypegenAt(logics, time.Now().UTC())
}

func EmitTypegenAt(logics []ParsedLogic, generatedAt time.Time) string {
	var builder strings.Builder

	builder.WriteString(fmt.Sprintf("// Generated by kea-typegen on %s. DO NOT EDIT THIS FILE MANUALLY.\n\n", generatedAt.Format(time.RFC1123)))
	builder.WriteString(fmt.Sprintf("import type { %s } from 'kea'\n", strings.Join(keaImports(logics), ", ")))

	imports := mergeImports(logics)
	if len(imports) > 0 {
		builder.WriteByte('\n')
		for _, item := range imports {
			for _, line := range renderImportLines(item) {
				builder.WriteString(line)
				builder.WriteByte('\n')
			}
		}
	}

	for index, logic := range logics {
		builder.WriteString("\n")
		if index > 0 {
			builder.WriteString("\n")
		}
		builder.WriteString(renderInterface(logic))
	}

	return builder.String()
}

func mergeImports(logics []ParsedLogic) []TypeImport {
	grouped := map[string]map[string]bool{}
	for _, logic := range logics {
		for _, item := range logic.Imports {
			if grouped[item.Path] == nil {
				grouped[item.Path] = map[string]bool{}
			}
			for _, name := range item.Names {
				grouped[item.Path][name] = true
			}
		}
	}

	paths := make([]string, 0, len(grouped))
	for path := range grouped {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	imports := make([]TypeImport, 0, len(paths))
	for _, path := range paths {
		names := make([]string, 0, len(grouped[path]))
		for name := range grouped[path] {
			names = append(names, name)
		}
		sort.Strings(names)
		imports = append(imports, TypeImport{Path: path, Names: names})
	}
	return imports
}

func renderImportLines(item TypeImport) []string {
	var namespaceSpecifiers []string
	var namedSpecifiers []string
	for _, name := range item.Names {
		if strings.HasPrefix(name, "* as ") {
			namespaceSpecifiers = append(namespaceSpecifiers, strings.TrimSpace(strings.TrimPrefix(name, "* as ")))
			continue
		}
		namedSpecifiers = append(namedSpecifiers, name)
	}

	lines := make([]string, 0, len(namespaceSpecifiers)+1)
	for _, alias := range namespaceSpecifiers {
		lines = append(lines, fmt.Sprintf("import type * as %s from '%s'", alias, item.Path))
	}
	if len(namedSpecifiers) > 0 {
		lines = append(lines, fmt.Sprintf("import type { %s } from '%s'", strings.Join(namedSpecifiers, ", "), item.Path))
	}
	return lines
}

func renderInterface(logic ParsedLogic) string {
	var builder strings.Builder

	builder.WriteString(fmt.Sprintf("export interface %s extends Logic {\n", logic.TypeName))
	writeProperty(&builder, "    ", "actionCreators", renderActionCreators(logic))
	writeProperty(&builder, "    ", "actionKeys", renderActionKeys(logic))
	writeProperty(&builder, "    ", "actionTypes", renderActionTypes(logic))
	writeProperty(&builder, "    ", "actions", renderActions(logic))
	writeProperty(&builder, "    ", "asyncActions", renderAsyncActions(logic))
	if logic.CustomType != "" {
		writeProperty(&builder, "    ", "custom", logic.CustomType)
	}
	writeProperty(&builder, "    ", "defaults", renderDefaults(logic.Reducers))
	writeProperty(&builder, "    ", "events", renderEvents(logic.Events))
	writeProperty(&builder, "    ", "key", fallbackType(logic.KeyType, "undefined"))
	writeProperty(&builder, "    ", "listeners", renderListeners(logic.Listeners))
	writeProperty(&builder, "    ", "path", renderPathTuple(logic.Path))
	writeProperty(&builder, "    ", "pathString", quoteString(logic.PathString))
	writeProperty(&builder, "    ", "props", fallbackType(logic.PropsType, "Record<string, unknown>"))
	writeProperty(&builder, "    ", "reducer", renderReducer(logic))
	writeProperty(&builder, "    ", "reducers", renderReducers(logic.Reducers))
	writeProperty(&builder, "    ", "selector", renderSelector(logic))
	writeProperty(&builder, "    ", "selectors", renderSelectors(logic))
	writeProperty(&builder, "    ", "sharedListeners", renderSharedListeners(logic.SharedListeners))
	writeProperty(&builder, "    ", "values", renderValues(logic))
	writeProperty(&builder, "    ", "_isKea", "true")
	writeProperty(&builder, "    ", "_isKeaWithKey", boolLiteral(logic.KeyType != ""))
	if len(logic.InternalSelectorTypes) > 0 {
		writeProperty(&builder, "    ", "__keaTypeGenInternalSelectorTypes", renderInternalSelectorTypes(logic.InternalSelectorTypes))
	}
	if len(logic.InternalReducerActions) > 0 {
		writeProperty(&builder, "    ", "__keaTypeGenInternalReducerActions", renderInternalReducerActions(logic.InternalReducerActions))
	}
	if logic.ExtraInputForm != "" {
		writeProperty(&builder, "    ", "__keaTypeGenInternalExtraInput", renderTypedFormInternalExtraInput(logic))
	}
	builder.WriteString("}\n")

	return builder.String()
}

func keaImports(logics []ParsedLogic) []string {
	imports := []string{"Logic"}
	for _, logic := range logics {
		if len(logic.SharedListeners) > 0 {
			imports = append(imports, "BreakPointFunction")
			break
		}
	}
	return imports
}

func renderActionTypes(logic ParsedLogic) string {
	if len(logic.Actions) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, action := range logic.Actions {
		lines = append(lines, fmt.Sprintf("    %s: %s", action.Name, quoteString(actionTypeString(logic, action.Name))))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderActionKeys(logic ParsedLogic) string {
	if len(logic.Actions) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, action := range logic.Actions {
		lines = append(lines, fmt.Sprintf("    %s: %s", quoteString(actionTypeString(logic, action.Name)), quoteString(action.Name)))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderActionCreators(logic ParsedLogic) string {
	if len(logic.Actions) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, action := range logic.Actions {
		parameters, _, ok := splitFunctionType(action.FunctionType)
		if !ok {
			parameters = "()"
		}
		payloadType := fallbackType(action.PayloadType, "any")
		lines = append(lines, fmt.Sprintf("    %s: %s => {", action.Name, parameters))
		lines = append(lines, fmt.Sprintf("        type: %s", quoteString(actionTypeString(logic, action.Name))))
		lines = append(lines, fmt.Sprintf("        payload: %s", payloadType))
		lines = append(lines, "    }")
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderActions(logic ParsedLogic) string {
	if len(logic.Actions) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, action := range logic.Actions {
		functionType := action.FunctionType
		parameters, _, ok := splitFunctionType(functionType)
		if ok {
			functionType = parameters + " => void"
		} else {
			functionType = "() => void"
		}
		lines = append(lines, fmt.Sprintf("    %s: %s", action.Name, functionType))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderListeners(listeners []ParsedListener) string {
	if len(listeners) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, listener := range listeners {
		lines = append(lines, fmt.Sprintf("    %s: ((action: %s, previousState: any) => void | Promise<void>)[]", renderPropertyName(listener.Name), listener.ActionType))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderAsyncActions(logic ParsedLogic) string {
	if len(logic.Actions) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, action := range logic.Actions {
		functionType := action.FunctionType
		parameters, _, ok := splitFunctionType(functionType)
		if ok {
			functionType = parameters + " => Promise<any>"
		} else {
			functionType = "() => Promise<any>"
		}
		lines = append(lines, fmt.Sprintf("    %s: %s", action.Name, functionType))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderDefaults(reducers []ParsedField) string {
	if len(reducers) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, reducer := range reducers {
		lines = append(lines, fmt.Sprintf("    %s: %s", reducer.Name, reducer.Type))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderEvents(events []string) string {
	if len(events) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, event := range events {
		lines = append(lines, fmt.Sprintf("    %s: () => void", event))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderReducers(reducers []ParsedField) string {
	if len(reducers) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, reducer := range reducers {
		lines = append(lines, fmt.Sprintf("    %s: (state: %s, action: any, fullState: any) => %s", reducer.Name, reducer.Type, reducer.Type))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderReducer(logic ParsedLogic) string {
	lines := []string{
		"(",
		"    state: any,",
		"    action: any,",
		"    fullState: any,",
		fmt.Sprintf(") => %s", renderFieldShape(logic.Reducers)),
	}
	return strings.Join(lines, "\n")
}

func renderSelector(logic ParsedLogic) string {
	lines := []string{
		"(",
		"    state: any,",
		fmt.Sprintf(") => %s", renderFieldShape(logic.Reducers)),
	}
	return strings.Join(lines, "\n")
}

func renderSelectors(logic ParsedLogic) string {
	selectors := mergedValueFields(logic)
	if len(selectors) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, selector := range selectors {
		lines = append(lines, fmt.Sprintf("    %s: (state: any, props?: any) => %s", selector.Name, selector.Type))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderSharedListeners(listeners []ParsedSharedListener) string {
	if len(listeners) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, listener := range listeners {
		lines = append(lines, fmt.Sprintf("    %s: (payload: %s, breakpoint: BreakPointFunction, action: %s, previousState: any) => void | Promise<void>", renderPropertyName(listener.Name), listener.PayloadType, listener.ActionType))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderValues(logic ParsedLogic) string {
	values := mergedValueFields(logic)
	if len(values) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, value := range values {
		lines = append(lines, fmt.Sprintf("    %s: %s", value.Name, value.Type))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderInternalSelectorTypes(selectors []ParsedFunction) string {
	if len(selectors) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, selector := range selectors {
		lines = append(lines, fmt.Sprintf("    %s: %s", selector.Name, selector.FunctionType))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderInternalReducerActions(actions []ParsedAction) string {
	if len(actions) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, action := range actions {
		parameters, _, ok := splitFunctionType(action.FunctionType)
		if !ok {
			parameters = "()"
		}
		payloadType := fallbackType(action.PayloadType, "any")
		lines = append(lines, fmt.Sprintf("    %s: %s => {", quoteString(action.Name), parameters))
		lines = append(lines, fmt.Sprintf("        payload: %s", payloadType))
		lines = append(lines, fmt.Sprintf("        type: %s", quoteString(action.Name)))
		lines = append(lines, "    }")
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func mergedValueFields(logic ParsedLogic) []ParsedField {
	return mergeParsedFields(logic.Reducers, logic.Selectors...)
}

func renderFieldShape(fields []ParsedField) string {
	if len(fields) == 0 {
		return "{}"
	}

	lines := []string{"{"}
	for _, field := range fields {
		lines = append(lines, fmt.Sprintf("    %s: %s", field.Name, field.Type))
	}
	lines = append(lines, "}")
	return strings.Join(lines, "\n")
}

func renderTypedFormInternalExtraInput(logic ParsedLogic) string {
	formType := logic.ExtraInputForm
	defaultType := "Record<string, any>"
	lines := []string{
		"{",
		"    form:",
		"        | {",
		fmt.Sprintf("              default?: %s", defaultType),
		fmt.Sprintf("              submit?: (form: %s) => void", formType),
		"          }",
		fmt.Sprintf("        | ((logic: %s) => {", logic.TypeName),
		fmt.Sprintf("              default?: %s", defaultType),
		fmt.Sprintf("              submit?: (form: %s) => void", formType),
		"          })",
		"}",
	}
	return strings.Join(lines, "\n")
}

func renderPathTuple(path []string) string {
	if len(path) == 0 {
		return "[]"
	}
	parts := make([]string, 0, len(path))
	for _, item := range path {
		parts = append(parts, quoteString(item))
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

func writeProperty(builder *strings.Builder, indent, name, typeText string) {
	lines := strings.Split(strings.TrimSpace(typeText), "\n")
	if len(lines) == 1 {
		builder.WriteString(fmt.Sprintf("%s%s: %s\n", indent, name, lines[0]))
		return
	}

	builder.WriteString(fmt.Sprintf("%s%s: %s\n", indent, name, lines[0]))
	for _, line := range lines[1:] {
		builder.WriteString(indent)
		builder.WriteString(line)
		builder.WriteByte('\n')
	}
}

func actionTypeString(logic ParsedLogic, actionName string) string {
	return camelCaseToWords(actionName) + " (" + logic.PathString + ")"
}

func camelCaseToWords(text string) string {
	var builder strings.Builder
	for index, r := range text {
		if r >= 'A' && r <= 'Z' {
			if index > 0 {
				builder.WriteByte(' ')
			}
			builder.WriteRune(r + ('a' - 'A'))
			continue
		}
		builder.WriteRune(r)
	}
	return builder.String()
}

func quoteString(text string) string {
	return "'" + strings.ReplaceAll(text, "'", "\\'") + "'"
}

func renderPropertyName(name string) string {
	if isSimpleIdentifier(name) {
		return name
	}
	return quoteString(name)
}

func isSimpleIdentifier(text string) bool {
	text = strings.TrimSpace(text)
	if text == "" {
		return false
	}
	for i := 0; i < len(text); i++ {
		ch := text[i]
		if i == 0 {
			if !isIdentifierStart(ch) {
				return false
			}
			continue
		}
		if !isIdentifierPart(ch) {
			return false
		}
	}
	return true
}

func fallbackType(value, fallback string) string {
	if strings.TrimSpace(value) == "" {
		return fallback
	}
	return value
}

func boolLiteral(value bool) string {
	if value {
		return "true"
	}
	return "false"
}
