package keainspect

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"kea-typegen/rewrite/internal/tsgoapi"
)

func TestBuildParsedLogicsFromSourcePropsLogic(t *testing.T) {
	root := repoRoot(t)
	sourcePath := filepath.Join(root, "samples", "propsLogic.ts")
	source := mustReadFile(t, sourcePath)

	report := &Report{
		ProjectDir: filepath.Join(root, "samples"),
		File:       sourcePath,
		Logics: []LogicReport{
			{
				Name:      "propsLogic",
				InputKind: "object",
				Sections: []SectionReport{
					{
						Name:                "props",
						EffectiveTypeString: "{ page: string; id: number; }",
						PrintedTypeNode:     "{\n    page: string;\n    id: number;\n}",
					},
					{
						Name:                "key",
						EffectiveTypeString: "number",
						PrintedTypeNode:     "number",
					},
					{
						Name: "actions",
						Members: []MemberReport{
							{Name: "setId", TypeString: "(id: number) => { id: number; }", ReturnTypeString: "{ id: number; }"},
							{Name: "setPage", TypeString: "(page: string) => { page: string; }", ReturnTypeString: "{ page: string; }"},
						},
					},
					{
						Name: "reducers",
						Members: []MemberReport{
							{Name: "currentPage", TypeString: "[string, { setPage: (_: string, { page }: { page: string; }) => string; }]"},
						},
					},
				},
			},
		},
	}

	logics, err := BuildParsedLogicsFromSource(report, source)
	if err != nil {
		t.Fatalf("BuildParsedLogicsFromSource returned error: %v", err)
	}
	if len(logics) != 1 {
		t.Fatalf("expected 1 parsed logic, got %d", len(logics))
	}

	logic := logics[0]
	if logic.PathString != "propsLogic.*" {
		t.Fatalf("expected path string %q, got %q", "propsLogic.*", logic.PathString)
	}
	if logic.KeyType != "number" {
		t.Fatalf("expected key type %q, got %q", "number", logic.KeyType)
	}
	if len(logic.Actions) != 2 {
		t.Fatalf("expected 2 actions, got %d", len(logic.Actions))
	}
	if len(logic.Reducers) != 1 || logic.Reducers[0].Type != "string" {
		t.Fatalf("expected string reducer, got %+v", logic.Reducers)
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	expected := `// Generated by kea-typegen on Wed, 11 Mar 2026 12:00:00 UTC. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface propsLogicType extends Logic {
    actionCreators: {
        setId: (id: number) => {
            type: 'set id (propsLogic.*)'
            payload: { id: number; }
        }
        setPage: (page: string) => {
            type: 'set page (propsLogic.*)'
            payload: { page: string; }
        }
    }
    actionKeys: {
        'set id (propsLogic.*)': 'setId'
        'set page (propsLogic.*)': 'setPage'
    }
    actionTypes: {
        setId: 'set id (propsLogic.*)'
        setPage: 'set page (propsLogic.*)'
    }
    actions: {
        setId: (id: number) => void
        setPage: (page: string) => void
    }
    asyncActions: {
        setId: (id: number) => Promise<any>
        setPage: (page: string) => Promise<any>
    }
    defaults: {
        currentPage: string
    }
    events: {}
    key: number
    listeners: {}
    path: ['propsLogic', '*']
    pathString: 'propsLogic.*'
    props: {
        page: string;
        id: number;
    }
    reducer: (
        state: any,
        action: any,
        fullState: any,
    ) => {
        currentPage: string
    }
    reducers: {
        currentPage: (state: string, action: any, fullState: any) => string
    }
    selector: (
        state: any,
    ) => {
        currentPage: string
    }
    selectors: {
        currentPage: (state: any, props?: any) => string
    }
    sharedListeners: {}
    values: {
        currentPage: string
    }
    _isKea: true
    _isKeaWithKey: true
}
`
	if rendered != expected {
		t.Fatalf("unexpected emitted typegen:\n%s", rendered)
	}
}

func TestBuildParsedLogicsCollectsImports(t *testing.T) {
	root := repoRoot(t)
	sourcePath := filepath.Join(root, "samples", "builderLogic.ts")
	source := mustReadFile(t, sourcePath)

	report := &Report{
		ProjectDir: filepath.Join(root, "samples"),
		File:       sourcePath,
		Logics: []LogicReport{
			{
				Name:      "builderLogic",
				InputKind: "builders",
				Sections: []SectionReport{
					{
						Name: "actions",
						Members: []MemberReport{
							{
								Name:             "setRepositories",
								TypeString:       "(repositories: Repository[]) => { repositories: Repository[]; }",
								ReturnTypeString: "{ repositories: Repository[]; }",
							},
						},
					},
					{
						Name: "reducers",
						Members: []MemberReport{
							{
								Name:       "repositories",
								TypeString: "[Repository[], { setRepositories: (_: Repository[], { repositories }: { repositories: Repository[]; }) => Repository[]; }]",
							},
						},
					},
				},
			},
		},
	}

	logics, err := BuildParsedLogicsFromSource(report, source)
	if err != nil {
		t.Fatalf("BuildParsedLogicsFromSource returned error: %v", err)
	}
	if len(logics) != 1 {
		t.Fatalf("expected 1 parsed logic, got %d", len(logics))
	}

	imports := logics[0].Imports
	if len(imports) != 1 {
		t.Fatalf("expected 1 import, got %+v", imports)
	}
	if imports[0].Path != "./types" {
		t.Fatalf("expected import path %q, got %q", "./types", imports[0].Path)
	}
	if len(imports[0].Names) != 1 || imports[0].Names[0] != "Repository" {
		t.Fatalf("expected Repository import, got %+v", imports[0].Names)
	}
}

func TestParseSelectorsPrefersReportedReturnType(t *testing.T) {
	section := SectionReport{
		Name: "selectors",
		Members: []MemberReport{
			{
				Name:             "capitalizedName",
				TypeString:       "[(s: { ... }) => [...], (name: string, number: number) => string]",
				ReturnTypeString: "string",
			},
		},
	}

	selectors := parseSelectors(section)
	if len(selectors) != 1 {
		t.Fatalf("expected 1 selector, got %+v", selectors)
	}
	if selectors[0].Type != "string" {
		t.Fatalf("expected selector type %q, got %q", "string", selectors[0].Type)
	}
}

func TestBuildParsedLogicsSynthesizesLoadersAndDefaults(t *testing.T) {
	root := repoRoot(t)
	sourcePath := filepath.Join(root, "samples", "logic.ts")
	source := mustReadFile(t, sourcePath)

	report := &Report{
		ProjectDir: filepath.Join(root, "samples"),
		File:       sourcePath,
		Logics: []LogicReport{
			{
				Name:      "logic",
				InputKind: "object",
				Sections: []SectionReport{
					{
						Name: "actions",
						Members: []MemberReport{
							{Name: "updateName", TypeString: "(name: string) => { name: string; }", ReturnTypeString: "{ name: string; }"},
						},
					},
					{
						Name: "defaults",
						Members: []MemberReport{
							{Name: "yetAnotherNameWithNullDefault", TypeString: "string | null"},
						},
					},
					{
						Name: "reducers",
						Members: []MemberReport{
							{Name: "name", TypeString: "[string, { updateName: (_: string, { name }: { name: string; }) => string; }]"},
							{Name: "otherNameNoDefault", TypeString: "{ updateName: (_: any, { name }: { name: string; }) => string; }"},
						},
					},
					{
						Name: "loaders",
						Members: []MemberReport{
							{Name: "sessions", TypeString: "{ __default: Session[]; loadSessions: (selectedDate: string) => Promise<Session[]>; }"},
						},
					},
					{
						Name: "listeners",
						Members: []MemberReport{
							{Name: "updateName", TypeString: "(payload: { name: string; }, previousState: any) => void"},
						},
					},
					{
						Name: "sharedListeners",
						Members: []MemberReport{
							{Name: "someRandomFunction", TypeString: "({ name }: { name: string; id?: number | undefined; }) => void"},
						},
					},
					{
						Name: "events",
						Members: []MemberReport{
							{Name: "afterMount", TypeString: "() => void"},
						},
					},
				},
			},
		},
	}

	logics, err := BuildParsedLogicsFromSource(report, source)
	if err != nil {
		t.Fatalf("BuildParsedLogicsFromSource returned error: %v", err)
	}
	logic := logics[0]

	if !hasAction(logic.Actions, "loadSessions") || !hasAction(logic.Actions, "loadSessionsSuccess") || !hasAction(logic.Actions, "loadSessionsFailure") {
		t.Fatalf("expected synthesized loader actions, got %+v", logic.Actions)
	}
	if !hasReducer(logic.Reducers, "sessions", "Session[]") || !hasReducer(logic.Reducers, "sessionsLoading", "boolean") {
		t.Fatalf("expected synthesized loader reducers, got %+v", logic.Reducers)
	}
	if !hasReducer(logic.Reducers, "yetAnotherNameWithNullDefault", "string | null") {
		t.Fatalf("expected defaults to merge into reducers, got %+v", logic.Reducers)
	}
	if !hasImport(logic.Imports, "./logic", "Session") {
		t.Fatalf("expected Session import from ./logic, got %+v", logic.Imports)
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	for _, expected := range []string{
		"import type { Logic, BreakPointFunction } from 'kea'",
		"import type { Session } from './logic'",
		"loadSessions: 'load sessions (scenes.homepage.index.*)'",
		"loadSessionsSuccess: 'load sessions success (scenes.homepage.index.*)'",
		"loadSessionsFailure: 'load sessions failure (scenes.homepage.index.*)'",
		"'updateName': ((action: { type: 'update name (scenes.homepage.index.*)'; payload: { name: string; } }, previousState: any) => void | Promise<void>)[]",
		"afterMount: () => void",
		"'someRandomFunction': (payload: { name: string; id?: number | undefined; }, breakpoint: BreakPointFunction, action: { type: string; payload: { name: string; id?: number | undefined; } }, previousState: any) => void | Promise<void>",
		"sessionsLoading: boolean",
		"payload?: string",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func TestBuildParsedLogicsWindowValuesSample(t *testing.T) {
	report := inspectSampleReport(t, "windowValuesLogic.ts")

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	if len(logics) != 1 {
		t.Fatalf("expected 1 parsed logic, got %d", len(logics))
	}

	logic := logics[0]
	if !hasReducer(logic.Reducers, "windowHeight", "number") || !hasReducer(logic.Reducers, "windowWidth", "number") {
		t.Fatalf("expected window values to be normalized into reducers, got %+v", logic.Reducers)
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	for _, expected := range []string{
		"windowHeight: number",
		"windowWidth: number",
		"windowHeight: (state: any, props?: any) => number",
		"windowWidth: (state: any, props?: any) => number",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func TestBuildParsedLogicsResolvesLocalConnectSections(t *testing.T) {
	report := inspectSampleReport(t, "autoImportLogic.ts")

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	if len(logics) != 1 {
		t.Fatalf("expected 1 parsed logic, got %d", len(logics))
	}

	logic := logics[0]
	if !hasAction(logic.Actions, "setRepositories") {
		t.Fatalf("expected connected action to be imported from githubLogic, got %+v", logic.Actions)
	}
	if selector, ok := findParsedField(logic.Selectors, "dashboard"); !ok || selector.Type != "Dashboard | null" {
		t.Fatalf("expected connected value dashboard: Dashboard | null, got %+v", logic.Selectors)
	}
	if !hasImport(logic.Imports, "./types", "Repository") || !hasImport(logic.Imports, "./types", "Dashboard") {
		t.Fatalf("expected connected imports from ./types, got %+v", logic.Imports)
	}
	if hasImport(logic.Imports, "kea/lib/playground/3.0/githubLogic", "Repository") {
		t.Fatalf("expected connected Repository import ownership to stay on ./types, got %+v", logic.Imports)
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	for _, expected := range []string{
		"setRepositories: (repositories: Repository[]) => void",
		"dashboard: (state: any, props?: any) => Dashboard | null",
		"dashboard: Dashboard | null",
		"import type { Dashboard, Repository } from './types'",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
	if strings.Contains(rendered, "kea/lib/playground/3.0/githubLogic") {
		t.Fatalf("expected rendered output to avoid synthetic package import for connected Repository:\n%s", rendered)
	}
}

func TestBuildParsedLogicsPrefersSymbolBackedConnectedValueTypes(t *testing.T) {
	report := inspectSampleReport(t, "githubConnectLogic.ts")

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	if len(logics) != 1 {
		t.Fatalf("expected 1 parsed logic, got %d", len(logics))
	}

	logic := logics[0]
	if selector, ok := findParsedField(logic.Selectors, "repositories"); !ok || selector.Type != "Repository[]" {
		t.Fatalf("expected connected repositories selector type Repository[], got %+v", selector)
	}
	if selector, ok := findParsedField(logic.Selectors, "isLoading"); !ok || selector.Type != "boolean" {
		t.Fatalf("expected connected isLoading selector type boolean, got %+v", selector)
	}
	if !hasImport(logic.Imports, "./types", "Repository") {
		t.Fatalf("expected Repository import from ./types, got %+v", logic.Imports)
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	for _, expected := range []string{
		"repositories: (state: any, props?: any) => Repository[]",
		"isLoading: (state: any, props?: any) => boolean",
		"repositories: Repository[]",
		"isLoading: boolean",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func TestBuildParsedLogicsAutoImportRichTypes(t *testing.T) {
	report := inspectSampleReport(t, "autoImportLogic.ts")

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	if len(logics) != 1 {
		t.Fatalf("expected 1 parsed logic, got %d", len(logics))
	}

	logic := logics[0]
	if selector, ok := findParsedField(logic.Selectors, "sbla"); !ok || selector.Type != "Partial<Record<string, S7>>" {
		t.Fatalf("expected selector sbla: Partial<Record<string, S7>>, got %+v", logic.Selectors)
	}
	for _, expectedImport := range []string{"D6", "R6", "S7", "RandomThing"} {
		if !hasImport(logic.Imports, "./autoImportTypes", expectedImport) {
			t.Fatalf("expected %s import from ./autoImportTypes, got %+v", expectedImport, logic.Imports)
		}
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	for _, expected := range []string{
		"sbla: (state: any, props?: any) => Partial<Record<string, S7>>",
		"sbla: Partial<Record<string, S7>>",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func TestBuildParsedLogicsPreservesSourceAliases(t *testing.T) {
	report := inspectSampleReport(t, "autoImportLogic.ts")

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	if len(logics) != 1 {
		t.Fatalf("expected 1 parsed logic, got %d", len(logics))
	}

	logic := logics[0]

	if action, ok := findParsedAction(logic.Actions, "actionA1"); !ok || !strings.Contains(action.FunctionType, "local1: L1") || !strings.Contains(action.FunctionType, "param2: A2") {
		t.Fatalf("expected actionA1 to preserve source aliases, got %+v", action)
	}
	if action, ok := findParsedAction(logic.Actions, "complexAction"); !ok || !strings.Contains(action.FunctionType, "timeout: NodeJS.Timeout") {
		t.Fatalf("expected complexAction timeout to preserve NodeJS.Timeout, got %+v", action)
	}
	if action, ok := findParsedAction(logic.Actions, "miscActionWithType"); !ok || !strings.Contains(action.FunctionType, "ExportedApi.RandomThing") || !strings.Contains(action.PayloadType, "ExportedApi.RandomThing") {
		t.Fatalf("expected miscActionWithType to preserve ExportedApi.RandomThing, got %+v", action)
	}
	if action, ok := findParsedAction(logic.Actions, "miscActionWithoutType"); !ok || !strings.Contains(action.FunctionType, "ExportedApi.RandomThing") || !strings.Contains(action.PayloadType, "RandomThing") {
		t.Fatalf("expected miscActionWithoutType to preserve source parameter alias and inferred payload, got %+v", action)
	}

	for _, expected := range []struct {
		name string
		typ  string
	}{
		{name: "asd", typ: "D6"},
		{name: "notimported", typ: "Bla"},
		{name: "rasd", typ: "R6"},
		{name: "then", typ: "null | ExportedApi.RandomThing"},
	} {
		if field, ok := findParsedField(logic.Reducers, expected.name); !ok || field.Type != expected.typ {
			t.Fatalf("expected reducer %s: %s, got %+v", expected.name, expected.typ, field)
		}
	}

	if selector, ok := findParsedField(logic.Selectors, "randomSpecifiedReturn"); !ok || selector.Type != "ExportedApi.RandomThing" {
		t.Fatalf("expected selector randomSpecifiedReturn: ExportedApi.RandomThing, got %+v", selector)
	}

	for _, expectedImport := range []struct {
		path string
		name string
	}{
		{path: "./autoImportLogic", name: "L1"},
		{path: "./donotimport", name: "Bla"},
		{path: "./autoImportTypes", name: "D6"},
		{path: "./autoImportTypes", name: "ExportedApi"},
		{path: "./autoImportTypes", name: "R6"},
	} {
		if !hasImport(logic.Imports, expectedImport.path, expectedImport.name) {
			t.Fatalf("expected import %s from %s, got %+v", expectedImport.name, expectedImport.path, logic.Imports)
		}
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	for _, expected := range []string{
		"local1: L1",
		"param2: A2",
		"timeout: NodeJS.Timeout",
		"miscActionWithType: (randomThing: ExportedApi.RandomThing) => void",
		"import type { Bla } from './donotimport'",
		"notimported: Bla",
		"rasd: R6",
		"randomSpecifiedReturn: (state: any, props?: any) => ExportedApi.RandomThing",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func TestBuildParsedLogicsNormalizesPluginSections(t *testing.T) {
	report := inspectSampleReport(t, "pluginLogic.ts")

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	if len(logics) != 2 {
		t.Fatalf("expected 2 parsed logics, got %d", len(logics))
	}

	pluginLogic := logics[0]
	if !hasAction(pluginLogic.Actions, "inlineAction") || !hasAction(pluginLogic.Actions, "submitForm") {
		t.Fatalf("expected inline/form plugin actions, got %+v", pluginLogic.Actions)
	}
	if !hasReducer(pluginLogic.Reducers, "inlineReducer", "{ asd: boolean }") {
		t.Fatalf("expected inlineReducer from inline plugin, got %+v", pluginLogic.Reducers)
	}
	if reducer, ok := findParsedField(pluginLogic.Reducers, "form"); !ok || !strings.Contains(reducer.Type, "name: string") || !strings.Contains(reducer.Type, "age: number") {
		t.Fatalf("expected form reducer type from plugin form defaults, got %+v", pluginLogic.Reducers)
	}

	anotherPluginLogic := logics[1]
	if !hasAction(anotherPluginLogic.Actions, "submitForm") {
		t.Fatalf("expected submitForm action for second plugin logic, got %+v", anotherPluginLogic.Actions)
	}
	if reducer, ok := findParsedField(anotherPluginLogic.Reducers, "form"); !ok || !strings.Contains(reducer.Type, "name: string") || !strings.Contains(reducer.Type, "age: number") {
		t.Fatalf("expected second form reducer type from plugin form defaults, got %+v", anotherPluginLogic.Reducers)
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	for _, expected := range []string{
		"inlineAction: () => void",
		"submitForm: () => void",
		"inlineReducer: { asd: boolean }",
		"form: { name: string; age: number; }",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func TestBuildParsedLogicsNormalizesTypedFormBuilder(t *testing.T) {
	report := inspectSampleReport(t, filepath.Join("typed-builder", "typedFormDemoLogic.ts"))

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	if len(logics) != 1 {
		t.Fatalf("expected 1 parsed logic, got %d", len(logics))
	}

	logic := logics[0]
	if !hasAction(logic.Actions, "submitForm") {
		t.Fatalf("expected submitForm action from typedForm builder, got %+v", logic.Actions)
	}
	if !hasReducer(logic.Reducers, "form", "Record<string, any>") {
		t.Fatalf("expected form reducer from typedForm builder, got %+v", logic.Reducers)
	}
	if logic.CustomType != "{\n    hello?: 'world'\n}" {
		t.Fatalf("expected typedForm custom field heuristic, got %q", logic.CustomType)
	}
	if logic.ExtraInputForm != "Record<string, any>" {
		t.Fatalf("expected typedForm extra input form type, got %q", logic.ExtraInputForm)
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	for _, expected := range []string{
		"submitForm: () => void",
		"form: Record<string, any>",
		"custom: {",
		"hello?: 'world'",
		"__keaTypeGenInternalExtraInput: {",
		"default?: Record<string, any>",
		"submit?: (form: Record<string, any>) => void",
		"| ((logic: typedFormDemoLogicType) => {",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func TestBuildParsedLogicsNormalizesBuilderForms(t *testing.T) {
	report := inspectSampleReport(t, "builderLogic.ts")

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	if len(logics) != 1 {
		t.Fatalf("expected 1 parsed logic, got %d", len(logics))
	}

	logic := logics[0]
	for _, expectedAction := range []string{
		"setMyFormValue",
		"setMyFormValues",
		"setMyFormManualErrors",
		"touchMyFormField",
		"resetMyForm",
		"submitMyForm",
		"submitMyFormRequest",
		"submitMyFormSuccess",
		"submitMyFormFailure",
	} {
		if !hasAction(logic.Actions, expectedAction) {
			t.Fatalf("expected %s action from forms builder, got %+v", expectedAction, logic.Actions)
		}
	}
	for _, expectedReducer := range []struct {
		name string
		typ  string
	}{
		{name: "isMyFormSubmitting", typ: "boolean"},
		{name: "showMyFormErrors", typ: "boolean"},
		{name: "myFormChanged", typ: "boolean"},
		{name: "myFormTouches", typ: "Record<string, boolean>"},
		{name: "myFormManualErrors", typ: "Record<string, any>"},
	} {
		if !hasReducer(logic.Reducers, expectedReducer.name, expectedReducer.typ) {
			t.Fatalf("expected reducer %s: %s, got %+v", expectedReducer.name, expectedReducer.typ, logic.Reducers)
		}
	}
	if reducer, ok := findParsedField(logic.Reducers, "myForm"); !ok || !strings.Contains(reducer.Type, "key1: string") || !strings.Contains(reducer.Type, "asd:") {
		t.Fatalf("expected myForm reducer type from forms defaults, got %+v", logic.Reducers)
	}
	if reducer, ok := findParsedField(logic.Reducers, "myForm"); !ok || strings.Contains(reducer.Type, "...") || !strings.Contains(reducer.Type, "key39: string") || !strings.Contains(reducer.Type, "asd: true") {
		t.Fatalf("expected myForm reducer type to keep the full expanded defaults shape, got %+v", reducer)
	}
	for _, expectedSelector := range []struct {
		name string
		typ  string
	}{
		{name: "myFormTouched", typ: "boolean"},
		{name: "myFormAllErrors", typ: "Record<string, any>"},
		{name: "myFormHasErrors", typ: "boolean"},
		{name: "isMyFormValid", typ: "boolean"},
	} {
		if selector, ok := findParsedField(logic.Selectors, expectedSelector.name); !ok || selector.Type != expectedSelector.typ {
			t.Fatalf("expected selector %s: %s, got %+v", expectedSelector.name, expectedSelector.typ, selector)
		}
	}
	if selector, ok := findParsedField(logic.Selectors, "myFormValidationErrors"); !ok || !strings.Contains(selector.Type, "DeepPartialMap<") || !strings.Contains(selector.Type, "ValidationErrorType") {
		t.Fatalf("expected myFormValidationErrors selector type, got %+v", logic.Selectors)
	}
	for _, actionName := range []string{"setMyFormValues", "resetMyForm", "submitMyFormRequest", "submitMyFormSuccess"} {
		action, ok := findParsedAction(logic.Actions, actionName)
		if !ok {
			t.Fatalf("expected %s action from forms builder, got %+v", actionName, logic.Actions)
		}
		if strings.Contains(action.FunctionType, "...") || strings.Contains(action.PayloadType, "...") || !strings.Contains(action.FunctionType, "key39: string") || !strings.Contains(action.FunctionType, "asd: true") {
			t.Fatalf("expected %s action type to keep the full expanded defaults shape, got %+v", actionName, action)
		}
	}
	for _, expectedImport := range []string{"DeepPartial", "DeepPartialMap", "FieldName", "ValidationErrorType"} {
		if !hasImport(logic.Imports, "kea-forms", expectedImport) {
			t.Fatalf("expected %s import from kea-forms, got %+v", expectedImport, logic.Imports)
		}
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	for _, expected := range []string{
		"import type { DeepPartial, DeepPartialMap, FieldName, ValidationErrorType } from 'kea-forms'",
		"setMyFormValue: (key: FieldName, value: any) => void",
		"submitMyFormFailure: (error: Error, errors: Record<string, any>) => void",
		"setMyFormValues: (values: DeepPartial<{ asd: true;",
		"myFormTouches: Record<string, boolean>",
		"myFormValidationErrors: (state: any, props?: any) => DeepPartialMap<",
		"isMyFormValid: (state: any, props?: any) => boolean",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func TestBuildParsedLogicsResolvesExternalConnectActionsFromSymbols(t *testing.T) {
	report := inspectSampleReport(t, "routerConnectLogic.ts")

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	logic := logics[0]

	action, ok := findParsedAction(logic.Actions, "locationChanged")
	if !ok {
		t.Fatalf("expected connected action for locationChanged, got %+v", logic.Actions)
	}
	if !strings.Contains(action.FunctionType, "LocationChangedPayload") {
		t.Fatalf("expected symbol-backed action type to preserve LocationChangedPayload, got %q", action.FunctionType)
	}
	if strings.Contains(action.PayloadType, "Record<...>") || !strings.Contains(action.PayloadType, "hashParams: Record<string, any>") {
		t.Fatalf("expected symbol-backed payload type to keep expanded Record<string, any> members, got %q", action.PayloadType)
	}
	if !hasImport(logic.Imports, "kea-router/lib/types", "LocationChangedPayload") {
		t.Fatalf("expected LocationChangedPayload import from kea-router/lib/types, got %+v", logic.Imports)
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	if strings.Contains(rendered, "{ type: string; payload: any }") || strings.Contains(rendered, "Record<...>") {
		t.Fatalf("expected listener typing to avoid generic connect fallback:\n%s", rendered)
	}
	for _, expected := range []string{
		"import type { LocationChangedPayload } from 'kea-router/lib/types'",
		"locationChanged: ({ method, pathname, search, searchParams, hash, hashParams, initial, }: LocationChangedPayload) => void",
		"'locationChanged': ((action: { type: 'location changed (containers.pages.main)'; payload:",
		"hashParams: Record<string, any>",
		"searchParams: Record<string, any>",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func TestBuildParsedLogicsResolvesNamespaceImportedConnectTargets(t *testing.T) {
	report := inspectSampleReport(t, "githubNamespaceConnectLogic.ts")

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	logic := logics[0]

	action, ok := findParsedAction(logic.Actions, "setRepositories")
	if !ok {
		t.Fatalf("expected connected action for setRepositories, got %+v", logic.Actions)
	}
	if !strings.Contains(action.FunctionType, "Repository[]") {
		t.Fatalf("expected connected namespace action type to preserve Repository[], got %+v", action)
	}
	if selector, ok := findParsedField(logic.Selectors, "repositories"); !ok || selector.Type != "Repository[]" {
		t.Fatalf("expected connected namespace repositories selector type Repository[], got %+v", selector)
	}
	if selector, ok := findParsedField(logic.Selectors, "githubIsLoading"); !ok || selector.Type != "boolean" {
		t.Fatalf("expected renamed namespace selector githubIsLoading: boolean, got %+v", selector)
	}
	if !hasImport(logic.Imports, "./types", "Repository") {
		t.Fatalf("expected Repository import from ./types, got %+v", logic.Imports)
	}

	listener, ok := findParsedListener(logic.Listeners, "set repositories (githubLogic)")
	if !ok {
		t.Fatalf("expected namespace-imported listener for set repositories (githubLogic), got %+v", logic.Listeners)
	}
	if listener.PayloadType != "{ repositories: Repository[]; }" {
		t.Fatalf("expected namespace-imported listener payload type { repositories: Repository[]; }, got %+v", listener)
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	for _, expected := range []string{
		"import type { Repository } from './types'",
		"setRepositories: (repositories: Repository[]) => void",
		"repositories: (state: any, props?: any) => Repository[]",
		"githubIsLoading: (state: any, props?: any) => boolean",
		"'set repositories (githubLogic)': ((action: { type: 'set repositories (githubLogic)'; payload: { repositories: Repository[]; } }, previousState: any) => void | Promise<void>)[]",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func TestBuildParsedLogicsResolvesImportedActionTypeListeners(t *testing.T) {
	report := inspectSampleReport(t, "githubImportLogic.ts")

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	logic := logics[0]

	listener, ok := findParsedListener(logic.Listeners, "set username (githubLogic)")
	if !ok {
		t.Fatalf("expected imported listener for set username (githubLogic), got %+v", logic.Listeners)
	}
	if listener.PayloadType != "{ username: string; }" {
		t.Fatalf("expected imported listener payload type { username: string; }, got %+v", listener)
	}
	if listener.ActionType != "{ type: 'set username (githubLogic)'; payload: { username: string; } }" {
		t.Fatalf("expected imported listener action type to be normalized, got %+v", listener)
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	if strings.Contains(rendered, "'set username (githubLogic)': ((action: { type: string; payload: any }, previousState: any) => void | Promise<void>)[]") {
		t.Fatalf("expected imported listener typing to avoid generic fallback:\n%s", rendered)
	}
	for _, expected := range []string{
		"'set username (githubLogic)': ((action: { type: 'set username (githubLogic)'; payload: { username: string; } }, previousState: any) => void | Promise<void>)[]",
		"repositorySelectorCopy: (state: any, props?: any) => Repository[]",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func TestBuildParsedLogicsNormalizesBooleanActionShorthands(t *testing.T) {
	report := inspectSampleReport(t, "complexLogic.ts")

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	logic := logics[0]

	for _, expected := range []struct {
		name         string
		functionType string
		payloadType  string
	}{
		{name: "deleteAction", functionType: "() => { value: true }", payloadType: "{ value: true }"},
		{name: "hideButtonActions", functionType: "() => { value: true }", payloadType: "{ value: true }"},
		{name: "incrementCounter", functionType: "() => { value: true }", payloadType: "{ value: true }"},
		{name: "showButtonActions", functionType: "() => { value: true }", payloadType: "{ value: true }"},
	} {
		action, ok := findParsedAction(logic.Actions, expected.name)
		if !ok {
			t.Fatalf("expected shorthand action %s, got %+v", expected.name, logic.Actions)
		}
		if action.FunctionType != expected.functionType || action.PayloadType != expected.payloadType {
			t.Fatalf("expected shorthand action %s to normalize to %q / %q, got %+v", expected.name, expected.functionType, expected.payloadType, action)
		}
	}

	listener, ok := findParsedListener(logic.Listeners, "hideButtonActions")
	if !ok {
		t.Fatalf("expected local hideButtonActions listener, got %+v", logic.Listeners)
	}
	if listener.PayloadType != "{ value: true }" {
		t.Fatalf("expected hideButtonActions listener payload type { value: true }, got %+v", listener)
	}
	if listener.ActionType != "{ type: 'hide button actions (complexLogic)'; payload: { value: true } }" {
		t.Fatalf("expected hideButtonActions listener action type to use shorthand payload, got %+v", listener)
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	for _, expected := range []string{
		"deleteAction: () => {",
		"payload: { value: true }",
		"'hideButtonActions': ((action: { type: 'hide button actions (complexLogic)'; payload: { value: true } }, previousState: any) => void | Promise<void>)[]",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func TestBuildParsedLogicsBuilderLazyLoaders(t *testing.T) {
	report := inspectSampleReport(t, "builderLogic.ts")

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	logic := logics[0]

	if !hasAction(logic.Actions, "initValue") || !hasAction(logic.Actions, "initValueSuccess") || !hasAction(logic.Actions, "initValueFailure") {
		t.Fatalf("expected synthesized lazy loader actions, got %+v", logic.Actions)
	}
	if !hasReducer(logic.Reducers, "lazyValue", "string") || !hasReducer(logic.Reducers, "lazyValueLoading", "boolean") {
		t.Fatalf("expected synthesized lazy loader reducers, got %+v", logic.Reducers)
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	for _, expected := range []string{
		"initValue: () => void",
		"initValueSuccess: (lazyValue: void, payload?: any) => void",
		"lazyValue: string",
		"lazyValueLoading: boolean",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func TestBuildParsedLogicsRecoversBuilderBlockSelectorReturnTypes(t *testing.T) {
	report := inspectSampleReport(t, "builderLogic.ts")

	logics, err := BuildParsedLogics(report)
	if err != nil {
		t.Fatalf("BuildParsedLogics returned error: %v", err)
	}
	logic := logics[0]

	if selector, ok := findParsedField(logic.Selectors, "sortedRepositories"); !ok || selector.Type != "Repository[]" {
		t.Fatalf("expected sortedRepositories selector type Repository[], got %+v", selector)
	}

	rendered := EmitTypegenAt(logics, time.Date(2026, time.March, 11, 12, 0, 0, 0, time.UTC))
	for _, expected := range []string{
		"sortedRepositories: (state: any, props?: any) => Repository[]",
		"sortedRepositories: Repository[]",
	} {
		if !strings.Contains(rendered, expected) {
			t.Fatalf("expected emitted output to contain %q:\n%s", expected, rendered)
		}
	}
}

func repoRoot(t *testing.T) string {
	t.Helper()
	root := filepath.Clean(filepath.Join("..", "..", ".."))
	abs, err := filepath.Abs(root)
	if err != nil {
		t.Fatalf("filepath.Abs returned error: %v", err)
	}
	return abs
}

func mustReadFile(t *testing.T, path string) string {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile returned error: %v", err)
	}
	return string(content)
}

func inspectSampleReport(t *testing.T, fileName string) *Report {
	t.Helper()
	root := repoRoot(t)
	report, err := InspectFile(context.Background(), InspectOptions{
		BinaryPath: tsgoapi.PreferredBinary(root),
		ProjectDir: filepath.Join(root, "samples"),
		ConfigFile: filepath.Join(root, "samples", "tsconfig.json"),
		File:       filepath.Join(root, "samples", fileName),
		Timeout:    15 * time.Second,
	})
	if err != nil {
		t.Fatalf("InspectFile returned error: %v", err)
	}
	return report
}

func hasAction(actions []ParsedAction, name string) bool {
	for _, action := range actions {
		if action.Name == name {
			return true
		}
	}
	return false
}

func hasReducer(reducers []ParsedField, name, typeText string) bool {
	for _, reducer := range reducers {
		if reducer.Name == name && reducer.Type == typeText {
			return true
		}
	}
	return false
}

func hasImport(imports []TypeImport, path, name string) bool {
	for _, item := range imports {
		if item.Path != path {
			continue
		}
		for _, imported := range item.Names {
			if imported == name {
				return true
			}
		}
	}
	return false
}

func findParsedListener(listeners []ParsedListener, name string) (ParsedListener, bool) {
	for _, listener := range listeners {
		if listener.Name == name {
			return listener, true
		}
	}
	return ParsedListener{}, false
}
