// Generated by kea-typegen on Thu, 22 May 2025 21:02:44 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { Repository } from './types'

export interface builderLogicType extends Logic {
    actionCreators: {
        setUsername: (username: string) => {
            type: 'set username (builderLogic)'
            payload: {
                username: string
            }
        }
        setRepositories: (repositories: Repository[]) => {
            type: 'set repositories (builderLogic)'
            payload: {
                repositories: Repository[]
            }
        }
        setFetchError: (error: string) => {
            type: 'set fetch error (builderLogic)'
            payload: {
                error: string
            }
        }
        initValue: () => {
            type: 'init value (builderLogic)'
            payload: any
        }
        initValueSuccess: (
            lazyValue: void,
            payload?: any,
        ) => {
            type: 'init value success (builderLogic)'
            payload: {
                lazyValue: void
                payload?: any
            }
        }
        initValueFailure: (
            error: string,
            errorObject?: any,
        ) => {
            type: 'init value failure (builderLogic)'
            payload: {
                error: string
                errorObject?: any
            }
        }
    }
    actionKeys: {
        'set username (builderLogic)': 'setUsername'
        'set repositories (builderLogic)': 'setRepositories'
        'set fetch error (builderLogic)': 'setFetchError'
        'init value (builderLogic)': 'initValue'
        'init value success (builderLogic)': 'initValueSuccess'
        'init value failure (builderLogic)': 'initValueFailure'
    }
    actionTypes: {
        setUsername: 'set username (builderLogic)'
        setRepositories: 'set repositories (builderLogic)'
        setFetchError: 'set fetch error (builderLogic)'
        initValue: 'init value (builderLogic)'
        initValueSuccess: 'init value success (builderLogic)'
        initValueFailure: 'init value failure (builderLogic)'
    }
    actions: {
        setUsername: (username: string) => void
        setRepositories: (repositories: Repository[]) => void
        setFetchError: (error: string) => void
        initValue: () => void
        initValueSuccess: (lazyValue: void, payload?: any) => void
        initValueFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        setUsername: (username: string) => Promise<any>
        setRepositories: (repositories: Repository[]) => Promise<any>
        setFetchError: (error: string) => Promise<any>
        initValue: () => Promise<any>
        initValueSuccess: (lazyValue: void, payload?: any) => Promise<any>
        initValueFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        username: string
        repositories: Repository[]
        isLoading: boolean
        error: string | null
        lazyValue: string
        lazyValueLoading: boolean
    }
    events: {
        afterMount: () => void
    }
    key: undefined
    listeners: {
        setUsername: ((
            action: {
                type: 'set username (builderLogic)'
                payload: {
                    username: string
                }
            },
            previousState: any,
        ) => void | Promise<void>)[]
    }
    path: ['builderLogic']
    pathString: 'builderLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any,
    ) => {
        username: string
        repositories: Repository[]
        isLoading: boolean
        error: string | null
        lazyValue: string
        lazyValueLoading: boolean
    }
    reducers: {
        username: (state: string, action: any, fullState: any) => string
        repositories: (state: Repository[], action: any, fullState: any) => Repository[]
        isLoading: (state: boolean, action: any, fullState: any) => boolean
        error: (state: string | null, action: any, fullState: any) => string | null
        lazyValue: (state: string, action: any, fullState: any) => string
        lazyValueLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (state: any) => {
        username: string
        repositories: Repository[]
        isLoading: boolean
        error: string | null
        lazyValue: string
        lazyValueLoading: boolean
    }
    selectors: {
        username: (state: any, props?: any) => string
        repositories: (state: any, props?: any) => Repository[]
        isLoading: (state: any, props?: any) => boolean
        error: (state: any, props?: any) => string | null
        lazyValue: (state: any, props?: any) => string
        lazyValueLoading: (state: any, props?: any) => boolean
        sortedRepositories: (state: any, props?: any) => Repository[]
    }
    sharedListeners: {}
    values: {
        username: string
        repositories: Repository[]
        isLoading: boolean
        error: string | null
        lazyValue: string
        lazyValueLoading: boolean
        sortedRepositories: Repository[]
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        sortedRepositories: (repositories: Repository[]) => Repository[]
    }
}
