// Generated by kea-typegen on Sun, 11 Jul 2021 21:29:06 GMT. DO NOT EDIT THIS FILE MANUALLY.

import { Logic } from 'kea'

export interface formsPluginLogicType extends Logic {
    actionCreators: {
        submitForm: () => {
            type: 'submit form (formsPluginLogic)'
            payload: {
                value: boolean
            }
        }
    }
    actionKeys: {
        'submit form (formsPluginLogic)': 'submitForm'
    }
    actionTypes: {
        submitForm: 'submit form (formsPluginLogic)'
    }
    actions: {
        submitForm: () => void
    }
    constants: {}
    defaults: {
        form: {
            asd: boolean
        }
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['formsPluginLogic']
    pathString: 'formsPluginLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: () => any,
        fullState: any,
    ) => {
        form: {
            asd: boolean
        }
    }
    reducerOptions: {}
    reducers: {
        form: (
            state: {
                asd: boolean
            },
            action: any,
            fullState: any,
        ) => {
            asd: boolean
        }
    }
    selector: (state: any) => {
        form: {
            asd: boolean
        }
    }
    selectors: {
        form: (
            state: any,
            props?: any,
        ) => {
            asd: boolean
        }
    }
    sharedListeners: {}
    values: {
        form: {
            asd: boolean
        }
    }
    _isKea: true
    _isKeaWithKey: false
}
