// Generated by kea-typegen on Sun, 11 Jul 2021 21:09:39 GMT. DO NOT EDIT THIS FILE MANUALLY.

import { Logic } from 'kea'

export interface formsPluginLogicType extends Logic {
    actionCreators: {
        ranFormsPlugin: () => {
            type: 'ran forms plugin (formsPluginLogic)'
            payload: {
                value: boolean
            }
        }
    }
    actionKeys: {
        'ran forms plugin (formsPluginLogic)': 'ranFormsPlugin'
    }
    actionTypes: {
        ranFormsPlugin: 'ran forms plugin (formsPluginLogic)'
    }
    actions: {
        ranFormsPlugin: () => void
    }
    constants: {}
    defaults: {}
    events: {}
    key: undefined
    listeners: {}
    path: ['formsPluginLogic']
    pathString: 'formsPluginLogic'
    props: Record<string, unknown>
    reducer: (state: any, action: () => any, fullState: any) => {}
    reducerOptions: {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {}
    sharedListeners: {}
    values: {}
    _isKea: true
    _isKeaWithKey: false
}
