// Generated by kea-typegen on Sun, 24 Apr 2022 19:04:33 GMT. DO NOT EDIT THIS FILE MANUALLY.

import { Logic } from 'kea'

export interface blaLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    defaults: {}
    events: {}
    key: undefined
    listeners: {}
    path: ['github']
    pathString: 'github'
    props: Record<string, unknown>
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {}
    sharedListeners: {}
    values: {}
    _isKea: true
    _isKeaWithKey: false
}
