// Generated by kea-typegen on Thu, 12 Mar 2026 22:21:05 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { Repository } from './types'

export interface githubNamespaceConnectLogicType extends Logic {
    actionCreators: {
        setRepositories: (repositories: Repository[]) => {
            type: 'set repositories (githubNamespaceConnectLogic)'
            payload: {
                repositories: Repository[]
            }
        }
    }
    actionKeys: {
        'set repositories (githubNamespaceConnectLogic)': 'setRepositories'
    }
    actionTypes: {
        setRepositories: 'set repositories (githubNamespaceConnectLogic)'
    }
    actions: {
        setRepositories: (repositories: Repository[]) => void
    }
    asyncActions: {
        setRepositories: (repositories: Repository[]) => Promise<any>
    }
    defaults: {}
    events: {}
    key: undefined
    listeners: {
        'set repositories (githubLogic)': ((
            action: {
                payload: {
                    repositories: Repository[]
                }
                type: 'set repositories (githubLogic)'
            },
            previousState: any,
        ) => void | Promise<void>)[]
    }
    path: ['githubNamespaceConnectLogic']
    pathString: 'githubNamespaceConnectLogic'
    props: Record<string, unknown>
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {
        repositories: (state: any, props?: any) => Repository[]
        githubIsLoading: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        repositories: Repository[]
        githubIsLoading: boolean
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalReducerActions: {
        'set repositories (githubLogic)': (repositories: Repository[]) => {
            payload: {
                repositories: Repository[]
            }
            type: 'set repositories (githubLogic)'
        }
    }
}
