// Generated by kea-typegen on Thu, 12 Mar 2026 22:21:05 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface pluginLogicType extends Logic {
    actionCreators: {
        submitForm: () => {
            type: 'submit form (pluginLogic)'
            payload: {
                value: boolean
            }
        }
    }
    actionKeys: {
        'submit form (pluginLogic)': 'submitForm'
    }
    actionTypes: {
        submitForm: 'submit form (pluginLogic)'
    }
    actions: {
        submitForm: () => void
    }
    asyncActions: {
        submitForm: () => Promise<any>
    }
    defaults: {
        form: {
            age: number
            name: string
        }
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['pluginLogic']
    pathString: 'pluginLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any,
    ) => {
        form: {
            age: number
            name: string
        }
    }
    reducers: {
        form: (
            state: {
                age: number
                name: string
            },
            action: any,
            fullState: any,
        ) => {
            age: number
            name: string
        }
    }
    selector: (state: any) => {
        form: {
            age: number
            name: string
        }
    }
    selectors: {
        form: (
            state: any,
            props?: any,
        ) => {
            age: number
            name: string
        }
    }
    sharedListeners: {}
    values: {
        form: {
            age: number
            name: string
        }
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalExtraInput: {
        form:
            | {
                  default?: Record<string, any>
                  submit?: (form: { age: number; name: string }) => void
              }
            | ((logic: pluginLogicType) => {
                  default?: Record<string, any>
                  submit?: (form: { age: number; name: string }) => void
              })
    }
}


export interface anotherPluginLogicType extends Logic {
    actionCreators: {
        submitForm: () => {
            type: 'submit form (anotherPluginLogic)'
            payload: {
                value: boolean
            }
        }
    }
    actionKeys: {
        'submit form (anotherPluginLogic)': 'submitForm'
    }
    actionTypes: {
        submitForm: 'submit form (anotherPluginLogic)'
    }
    actions: {
        submitForm: () => void
    }
    asyncActions: {
        submitForm: () => Promise<any>
    }
    defaults: {
        form: {
            age: number
            name: string
        }
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['anotherPluginLogic']
    pathString: 'anotherPluginLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any,
    ) => {
        form: {
            age: number
            name: string
        }
    }
    reducers: {
        form: (
            state: {
                age: number
                name: string
            },
            action: any,
            fullState: any,
        ) => {
            age: number
            name: string
        }
    }
    selector: (state: any) => {
        form: {
            age: number
            name: string
        }
    }
    selectors: {
        form: (
            state: any,
            props?: any,
        ) => {
            age: number
            name: string
        }
    }
    sharedListeners: {}
    values: {
        form: {
            age: number
            name: string
        }
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalExtraInput: {
        form:
            | {
                  default?: Record<string, any>
                  submit?: (form: { age: number; name: string }) => void
              }
            | ((logic: anotherPluginLogicType) => {
                  default?: Record<string, any>
                  submit?: (form: { age: number; name: string }) => void
              })
    }
}
