// Generated by kea-typegen on Thu, 12 Mar 2026 22:57:34 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { ExperimentsResult, FeatureFlagsResult } from './posthogCanaryTypes'

export interface posthogSetLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    asyncActions: {}
    defaults: {
        featureFlags: FeatureFlagsResult
        experiments: ExperimentsResult
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['posthogSetLogic']
    pathString: 'posthogSetLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any,
    ) => {
        featureFlags: FeatureFlagsResult
        experiments: ExperimentsResult
    }
    reducers: {
        featureFlags: (state: FeatureFlagsResult, action: any, fullState: any) => FeatureFlagsResult
        experiments: (state: ExperimentsResult, action: any, fullState: any) => ExperimentsResult
    }
    selector: (state: any) => {
        featureFlags: FeatureFlagsResult
        experiments: ExperimentsResult
    }
    selectors: {
        featureFlags: (state: any, props?: any) => FeatureFlagsResult
        experiments: (state: any, props?: any) => ExperimentsResult
        unavailableFeatureFlagKeys: (state: any, props?: any) => Set<string>
    }
    sharedListeners: {}
    values: {
        featureFlags: FeatureFlagsResult
        experiments: ExperimentsResult
        unavailableFeatureFlagKeys: Set<string>
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        unavailableFeatureFlagKeys: (featureFlags: FeatureFlagsResult, experiments: ExperimentsResult) => Set<string>
    }
}
