// Generated by kea-typegen on Thu, 12 Mar 2026 22:57:34 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { GroupType } from './posthogCanaryTypes'

export interface posthogMapLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    asyncActions: {}
    defaults: {
        groupTypesRaw: GroupType[]
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['posthogMapLogic']
    pathString: 'posthogMapLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any,
    ) => {
        groupTypesRaw: GroupType[]
    }
    reducers: {
        groupTypesRaw: (state: GroupType[], action: any, fullState: any) => GroupType[]
    }
    selector: (state: any) => {
        groupTypesRaw: GroupType[]
    }
    selectors: {
        groupTypesRaw: (state: any, props?: any) => GroupType[]
        groupTypes: (state: any, props?: any) => Map<number, GroupType>
    }
    sharedListeners: {}
    values: {
        groupTypesRaw: GroupType[]
        groupTypes: Map<number, GroupType>
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        groupTypes: (groupTypesRaw: GroupType[]) => Map<number, GroupType>
    }
}
