// Generated by kea-typegen on Thu, 12 Mar 2026 22:57:35 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { GroupType } from './posthogCanaryTypes'

export interface posthogMapConnectLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    asyncActions: {}
    defaults: {}
    events: {}
    key: undefined
    listeners: {}
    path: ['posthogMapConnectLogic']
    pathString: 'posthogMapConnectLogic'
    props: Record<string, unknown>
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {
        groupTypes: (state: any, props?: any) => Map<number, GroupType>
        groupNames: (state: any, props?: any) => string[]
    }
    sharedListeners: {}
    values: {
        groupTypes: Map<number, GroupType>
        groupNames: string[]
    }
    _isKea: true
    _isKeaWithKey: false
    __keaTypeGenInternalSelectorTypes: {
        groupNames: (
            groupTypes: Map<
                number,
                import('/Users/marius/Projects/Kea/kea-typegen/samples/posthogCanaryTypes').GroupType
            >,
        ) => string[]
    }
}
