// Generated by kea-typegen on Thu, 12 Mar 2026 22:57:35 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { PosthogBuilderPropsKeyLogicProps } from './posthogBuilderPropsKeyLogic'

export interface posthogBuilderPropsKeyLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    asyncActions: {}
    defaults: {}
    events: {}
    key: string
    listeners: {}
    path: ['posthogBuilderPropsKeyLogic', '*']
    pathString: 'posthogBuilderPropsKeyLogic.*'
    props: PosthogBuilderPropsKeyLogicProps
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {
        endpoint: (state: any, props?: any) => string
        humanReadableResource: (state: any, props?: any) => string
    }
    sharedListeners: {}
    values: {
        endpoint: string
        humanReadableResource: string
    }
    _isKea: true
    _isKeaWithKey: true
    __keaTypeGenInternalSelectorTypes: {
        endpoint: (resource: 'feature_flag' | 'project', resourceId: string) => string
        humanReadableResource: (resource: 'feature_flag' | 'project') => string
    }
}
