// Generated by kea-typegen on Sun, 12 Dec 2021 13:38:14 GMT. DO NOT EDIT THIS FILE MANUALLY.

import { Logic } from 'kea'

export interface propsLogicType extends Logic {
    actionCreators: {
        setPage: (page: string) => {
            type: 'set page (propsLogic.*)'
            payload: {
                page: string
            }
        }
        setId: (id: number) => {
            type: 'set id (propsLogic.*)'
            payload: {
                id: number
            }
        }
    }
    actionKeys: {
        'set page (propsLogic.*)': 'setPage'
        'set id (propsLogic.*)': 'setId'
    }
    actionTypes: {
        setPage: 'set page (propsLogic.*)'
        setId: 'set id (propsLogic.*)'
    }
    actions: {
        setPage: (page: string) => void
        setId: (id: number) => void
    }
    constants: {}
    defaults: {
        currentPage: string
    }
    events: {}
    key: number
    listeners: {}
    path: ['propsLogic', '*']
    pathString: 'propsLogic.*'
    props: {
        page: string
        id: number
    }
    reducer: (
        state: any,
        action: () => any,
        fullState: any,
    ) => {
        currentPage: string
    }
    reducerOptions: {}
    reducers: {
        currentPage: (state: string, action: any, fullState: any) => string
    }
    selector: (state: any) => {
        currentPage: string
    }
    selectors: {
        currentPage: (state: any, props?: any) => string
    }
    sharedListeners: {}
    values: {
        currentPage: string
    }
    _isKea: true
    _isKeaWithKey: true
}
