// Generated by kea-typegen on Wed, 16 Aug 2023 12:58:35 GMT. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

import type { LocationChangedPayload } from 'kea-router/lib/types.d'

export interface routerConnectLogicType extends Logic {
    actionCreators: {
        locationChanged: ({
            method,
            pathname,
            search,
            searchParams,
            hash,
            hashParams,
            initial,
        }: LocationChangedPayload) => {
            type: 'location changed (containers.pages.main)'
            payload: {
                method: 'PUSH' | 'REPLACE' | 'POP'
                pathname: string
                search: string
                searchParams: Record<string, any>
                hash: string
                hashParams: Record<string, any>
                initial: boolean
            }
        }
    }
    actionKeys: {
        'location changed (containers.pages.main)': 'locationChanged'
    }
    actionTypes: {
        locationChanged: 'location changed (containers.pages.main)'
    }
    actions: {
        locationChanged: ({
            method,
            pathname,
            search,
            searchParams,
            hash,
            hashParams,
            initial,
        }: LocationChangedPayload) => void
    }
    asyncActions: {
        locationChanged: ({
            method,
            pathname,
            search,
            searchParams,
            hash,
            hashParams,
            initial,
        }: LocationChangedPayload) => Promise<any>
    }
    defaults: {}
    events: {}
    key: undefined
    listeners: {
        locationChanged: ((
            action: {
                type: 'location changed (containers.pages.main)'
                payload: {
                    method: 'PUSH' | 'REPLACE' | 'POP'
                    pathname: string
                    search: string
                    searchParams: Record<string, any>
                    hash: string
                    hashParams: Record<string, any>
                    initial: boolean
                }
            },
            previousState: any,
        ) => void | Promise<void>)[]
    }
    path: ['containers', 'pages', 'main']
    pathString: 'containers.pages.main'
    props: Record<string, unknown>
    reducer: (state: any, action: any, fullState: any) => {}
    reducers: {}
    selector: (state: any) => {}
    selectors: {}
    sharedListeners: {}
    values: {}
    _isKea: true
    _isKeaWithKey: false
}
