// Generated by kea-typegen on Sun, 03 Apr 2022 21:00:56 GMT. DO NOT EDIT THIS FILE MANUALLY.

import { Logic } from 'kea'

export interface windowValuesLogicType extends Logic {
    actionCreators: {}
    actionKeys: {}
    actionTypes: {}
    actions: {}
    defaults: {
        windowHeight: number
        windowWidth: number
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['windowValuesLogic']
    pathString: 'windowValuesLogic'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any,
    ) => {
        windowHeight: number
        windowWidth: number
    }
    reducers: {
        windowHeight: (state: number, action: any, fullState: any) => number
        windowWidth: (state: number, action: any, fullState: any) => number
    }
    selector: (state: any) => {
        windowHeight: number
        windowWidth: number
    }
    selectors: {
        windowHeight: (state: any, props?: any) => number
        windowWidth: (state: any, props?: any) => number
    }
    sharedListeners: {}
    values: {
        windowHeight: number
        windowWidth: number
    }
    _isKea: true
    _isKeaWithKey: false
}
