// Generated by kea-typegen on Wed, 11 Mar 2026 20:44:20 UTC. DO NOT EDIT THIS FILE MANUALLY.

import type { Logic } from 'kea'

export interface logicType extends Logic {
    actionCreators: {
        loadSessions: (query: string) => {
            type: 'load sessions (src.__tests__.e2e.loaders)'
            payload: string
        }
        loadSessionsSuccess: (sessions: Session[], payload?: string) => {
            type: 'load sessions success (src.__tests__.e2e.loaders)'
            payload: { sessions: Session[]; payload?: string }
        }
        loadSessionsFailure: (error: string, errorObject?: any) => {
            type: 'load sessions failure (src.__tests__.e2e.loaders)'
            payload: { error: string; errorObject?: any }
        }
    }
    actionKeys: {
        'load sessions (src.__tests__.e2e.loaders)': 'loadSessions'
        'load sessions success (src.__tests__.e2e.loaders)': 'loadSessionsSuccess'
        'load sessions failure (src.__tests__.e2e.loaders)': 'loadSessionsFailure'
    }
    actionTypes: {
        loadSessions: 'load sessions (src.__tests__.e2e.loaders)'
        loadSessionsSuccess: 'load sessions success (src.__tests__.e2e.loaders)'
        loadSessionsFailure: 'load sessions failure (src.__tests__.e2e.loaders)'
    }
    actions: {
        loadSessions: (query: string) => void
        loadSessionsSuccess: (sessions: Session[], payload?: string) => void
        loadSessionsFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        loadSessions: (query: string) => Promise<any>
        loadSessionsSuccess: (sessions: Session[], payload?: string) => Promise<any>
        loadSessionsFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        sessions: Session[]
        sessionsLoading: boolean
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['src', '__tests__', 'e2e', 'loaders']
    pathString: 'src.__tests__.e2e.loaders'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any,
    ) => {
        sessions: Session[]
        sessionsLoading: boolean
    }
    reducers: {
        sessions: (state: Session[], action: any, fullState: any) => Session[]
        sessionsLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (
        state: any,
    ) => {
        sessions: Session[]
        sessionsLoading: boolean
    }
    selectors: {
        sessions: (state: any, props?: any) => Session[]
        sessionsLoading: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        sessions: Session[]
        sessionsLoading: boolean
    }
    _isKea: true
    _isKeaWithKey: false
}


export interface logicType extends Logic {
    actionCreators: {
        loadSessions: (query: string) => {
            type: 'load sessions (src.__tests__.e2e.loaders)'
            payload: string
        }
        loadSessionsSuccess: (sessions: Session[], payload?: string) => {
            type: 'load sessions success (src.__tests__.e2e.loaders)'
            payload: { sessions: Session[]; payload?: string }
        }
        loadSessionsFailure: (error: string, errorObject?: any) => {
            type: 'load sessions failure (src.__tests__.e2e.loaders)'
            payload: { error: string; errorObject?: any }
        }
    }
    actionKeys: {
        'load sessions (src.__tests__.e2e.loaders)': 'loadSessions'
        'load sessions success (src.__tests__.e2e.loaders)': 'loadSessionsSuccess'
        'load sessions failure (src.__tests__.e2e.loaders)': 'loadSessionsFailure'
    }
    actionTypes: {
        loadSessions: 'load sessions (src.__tests__.e2e.loaders)'
        loadSessionsSuccess: 'load sessions success (src.__tests__.e2e.loaders)'
        loadSessionsFailure: 'load sessions failure (src.__tests__.e2e.loaders)'
    }
    actions: {
        loadSessions: (query: string) => void
        loadSessionsSuccess: (sessions: Session[], payload?: string) => void
        loadSessionsFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        loadSessions: (query: string) => Promise<any>
        loadSessionsSuccess: (sessions: Session[], payload?: string) => Promise<any>
        loadSessionsFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        sessions: Session[]
        sessionsLoading: boolean
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['src', '__tests__', 'e2e', 'loaders']
    pathString: 'src.__tests__.e2e.loaders'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any,
    ) => {
        sessions: Session[]
        sessionsLoading: boolean
    }
    reducers: {
        sessions: (state: Session[], action: any, fullState: any) => Session[]
        sessionsLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (
        state: any,
    ) => {
        sessions: Session[]
        sessionsLoading: boolean
    }
    selectors: {
        sessions: (state: any, props?: any) => Session[]
        sessionsLoading: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        sessions: Session[]
        sessionsLoading: boolean
    }
    _isKea: true
    _isKeaWithKey: false
}


export interface logicType extends Logic {
    actionCreators: {
        loadResults: () => {
            type: 'load results (src.__tests__.e2e.loaders)'
            payload: any
        }
        loadResultsSuccess: () => {
            type: 'load results success (src.__tests__.e2e.loaders)'
            payload: { sessions: "\n import { kea } from 'kea'\n const logic = kea<logicType>({\n loaders: ({ actions }) => ({\n sessions: [\n [] as string[],\n {\n loadSessions: () => [],\n loadResults: async () => {\n ...; payload?: any }
        }
        loadResultsFailure: (error: string, errorObject?: any) => {
            type: 'load results failure (src.__tests__.e2e.loaders)'
            payload: { error: string; errorObject?: any }
        }
        loadSessions: () => {
            type: 'load sessions (src.__tests__.e2e.loaders)'
            payload: any
        }
        loadSessionsSuccess: () => {
            type: 'load sessions success (src.__tests__.e2e.loaders)'
            payload: { sessions: "\n import { kea } from 'kea'\n const logic = kea<logicType>({\n loaders: ({ actions }) => ({\n sessions: [\n [] as string[],\n {\n loadSessions: () => [],\n loadResults: async () => {\n ...; payload?: any }
        }
        loadSessionsFailure: (error: string, errorObject?: any) => {
            type: 'load sessions failure (src.__tests__.e2e.loaders)'
            payload: { error: string; errorObject?: any }
        }
    }
    actionKeys: {
        'load results (src.__tests__.e2e.loaders)': 'loadResults'
        'load results success (src.__tests__.e2e.loaders)': 'loadResultsSuccess'
        'load results failure (src.__tests__.e2e.loaders)': 'loadResultsFailure'
        'load sessions (src.__tests__.e2e.loaders)': 'loadSessions'
        'load sessions success (src.__tests__.e2e.loaders)': 'loadSessionsSuccess'
        'load sessions failure (src.__tests__.e2e.loaders)': 'loadSessionsFailure'
    }
    actionTypes: {
        loadResults: 'load results (src.__tests__.e2e.loaders)'
        loadResultsSuccess: 'load results success (src.__tests__.e2e.loaders)'
        loadResultsFailure: 'load results failure (src.__tests__.e2e.loaders)'
        loadSessions: 'load sessions (src.__tests__.e2e.loaders)'
        loadSessionsSuccess: 'load sessions success (src.__tests__.e2e.loaders)'
        loadSessionsFailure: 'load sessions failure (src.__tests__.e2e.loaders)'
    }
    actions: {
        loadResults: () => void
        loadResultsSuccess: () => void
        loadResultsFailure: (error: string, errorObject?: any) => void
        loadSessions: () => void
        loadSessionsSuccess: () => void
        loadSessionsFailure: (error: string, errorObject?: any) => void
    }
    asyncActions: {
        loadResults: () => Promise<any>
        loadResultsSuccess: () => Promise<any>
        loadResultsFailure: (error: string, errorObject?: any) => Promise<any>
        loadSessions: () => Promise<any>
        loadSessionsSuccess: () => Promise<any>
        loadSessionsFailure: (error: string, errorObject?: any) => Promise<any>
    }
    defaults: {
        sessions: string[]
        sessionsLoading: boolean
    }
    events: {}
    key: undefined
    listeners: {}
    path: ['src', '__tests__', 'e2e', 'loaders']
    pathString: 'src.__tests__.e2e.loaders'
    props: Record<string, unknown>
    reducer: (
        state: any,
        action: any,
        fullState: any,
    ) => {
        sessions: string[]
        sessionsLoading: boolean
    }
    reducers: {
        sessions: (state: string[], action: any, fullState: any) => string[]
        sessionsLoading: (state: boolean, action: any, fullState: any) => boolean
    }
    selector: (
        state: any,
    ) => {
        sessions: string[]
        sessionsLoading: boolean
    }
    selectors: {
        sessions: (state: any, props?: any) => string[]
        sessionsLoading: (state: any, props?: any) => boolean
    }
    sharedListeners: {}
    values: {
        sessions: string[]
        sessionsLoading: boolean
    }
    _isKea: true
    _isKeaWithKey: false
}
